### ISSUE TITLE
开摄像头时时绿花屏 

### ISSUE THREAD

**Issue by vistal8** [w2016561536/android_virtual_cam#108]
尝试过1920X1080 和720 都不行，请问这个视频是根据什么来设置的

**Comment by vistal8** [comment]
摄像头模式正常，但是开启直播的时候是绿花屏

**Comment by vistal8** [comment]
视频分辨率 是根据什么设置的

**Comment by vistal8** [comment]
05-08 13:02:16.108 I/Xposed  ( 9130): 【VCAM】createCaptureSession创捷捕获，原始:[Surface(name=android.graphics.SurfaceTexture@509b224)/@0x540018d]虚拟：Surface(name=android.graphics.SurfaceTexture@509b224)/@0x540018d
05-08 13:02:16.109 E/Xposed  ( 9130): java.lang.NoSuchMethodError: com.xunmeng.pdd_av_foundation.androidcamera.o0.a.k$b#onClosed(android.hardware.camera2.CameraCaptureSession)#exact
05-08 13:02:16.109 E/Xposed  ( 9130): 	at de.robv.android.xposed.XposedHelpers.findMethodExact(XposedHelpers.java:331)
05-08 13:02:16.109 E/Xposed  ( 9130): 	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:183)
05-08 13:02:16.109 E/Xposed  ( 9130): 	at com.example.vcam.HookMain.process_camera2Session_callback(HookMain.java:1176)
05-08 13:02:16.109 E/Xposed  ( 9130): 	at com.example.vcam.HookMain.access$600(HookMain.java:43)
05-08 13:02:16.109 E/Xposed  ( 9130): 	at com.example.vcam.HookMain$20$1.beforeHookedMethod(HookMain.java:867)
05-08 13:02:16.109 E/Xposed  ( 9130): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:344)
05-08 13:02:16.109 E/Xposed  ( 9130): 	at android.hardware.camera2.impl.CameraDeviceImpl.createCaptureSession(<Xposed>)
05-08 13:02:16.109 E/Xposed  ( 9130): 	at com.xunmeng.pdd_av_foundation.androidcamera.o0.a.k.g0(Camera2Impl.java:29)
05-08 13:02:16.109 E/Xposed  ( 9130): 	at com.xunmeng.pdd_av_foundation.androidcamera.o0.a.k$a.onOpened(Camera2Impl.java:3)
05-08 13:02:16.109 E/Xposed  ( 9130): 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
05-08 13:02:16.109 E/Xposed  ( 9130): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:364)
05-08 13:02:16.109 E/Xposed  ( 9130): 	at com.xunmeng.pdd_av_foundation.androidcamera.o0.a.k$a.onOpened(<Xposed>)
05-08 13:02:16.109 E/Xposed  ( 9130): 	at android.hardware.camera2.impl.CameraDeviceImpl$1.run(CameraDeviceImpl.java)
05-08 13:02:16.109 E/Xposed  ( 9130): 	at android.os.Handler.handleCallback(Handler.java)
05-08 13:02:16.109 E/Xposed  ( 9130): 	at android.os.Handler.dispatchMessage(Handler.java)
05-08 13:02:16.109 E/Xposed  ( 9130): 	at com.xunmeng.pinduoduo.threadpool.i$d.dispatchMessage(PddHandler.java:3)
05-08 13:02:16.109 E/Xposed  ( 9130): 	at android.os.Looper.loop(Looper.java)
05-08 13:02:16.109 E/Xposed  ( 9130): 	at android.os.HandlerThread.run(HandlerThread.java)
05-08 13:02:16.174 I/Xposed  ( 9130): 【VCAM】onConfigured ：android.hardware.camera2.impl.CameraCaptureSessionImpl@44b1695
05-08 13:02:16.174 I/Xposed  ( 9130): 【VCAM】onConfigured ：android.hardware.camera2.impl.CameraCaptureSessionImpl@44b1695
05-08 13:02:16.174 I/Xposed  ( 9130): 【VCAM】onConfigured ：android.hardware.camera2.impl.CameraCaptureSessionImpl@44b1695
05-08 13:02:16.174 I/Xposed  ( 9130): 【VCAM】onConfigured ：android.hardware.camera2.impl.CameraCaptureSessionImpl@44b1695
05-08 13:02:16.174 I/Xposed  ( 9130): 【VCAM】onConfigured ：android.hardware.camera2.impl.CameraCaptureSessionImpl@44b1695
05-08 13:02:16.174 I/Xposed  ( 9130): 【VCAM】onConfigured ：android.hardware.camera2.impl.CameraCaptureSessionImpl@44b1695
05-08 13:02:16.174 I/Xposed  ( 9130): 【VCAM】onConfigured ：android.hardware.camera2.impl.CameraCaptureSessionImpl@44b1695
05-08 13:02:16.174 I/Xposed  ( 9130): 【VCAM】onConfigured ：android.hardware.camera2.impl.CameraCaptureSessionImpl@44b1695
05-08 13:02:16.174 I/Xposed  ( 9130): 【VCAM】onConfigured ：android.hardware.camera2.impl.CameraCaptureSessionImpl@44b1695
05-08 13:02:16.174 I/Xposed  ( 9130): 【VCAM】onConfigured ：android.hardware.camera2.impl.CameraCaptureSessionImpl@44b1695
05-08 13:02:16.175 I/Xposed  ( 9130): 【VCAM】onConfigured ：android.hardware.camera2.impl.CameraCaptureSessionImpl@44b1695
05-08 13:02:16.175 I/Xposed  ( 9130): 【VCAM】onConfigured ：android.hardware.camera2.impl.CameraCaptureSessionImpl@44b1695
05-08 13:02:16.175 I/Xposed  ( 9130): 【VCAM】onConfigured ：android.hardware.camera2.impl.CameraCaptureSessionImpl@44b1695
05-08 13:02:16.175 I/Xposed  ( 9130): 【VCAM】onConfigured ：android.hardware.camera2.impl.CameraCaptureSessionImpl@44b1695
05-08 13:02:16.175 I/Xposed  ( 9130): 【VCAM】onConfigured ：android.hardware.camera2.impl.CameraCaptureSessionImpl@44b1695
05-08 13:02:16.175 I/Xposed  ( 9130): 【VCAM】onConfigured ：android.hardware.camera2.impl.CameraCaptureSessionImpl@44b1695
05-08 13:02:16.175 I/Xposed  ( 9130): 【VCAM】onConfigured ：android.hardware.camera2.impl.CameraCaptureSessionImpl@44b1695
05-08 13:02:16.175 I/Xposed  ( 9130): 【VCAM】onConfigured ：android.hardware.camera2.impl.CameraCaptureSessionImpl@44b1695
05-08 13:02:16.175 I/Xposed  ( 9130): 【VCAM】onConfigured ：android.hardware.camera2.impl.CameraCaptureSessionImpl@44b1695
05-08 13:02:16.175 I/Xposed  ( 9130): 【VCAM】onConfigured ：android.hardware.camera2.impl.CameraCaptureSessionImpl@44b1695
05-08 13:02:16.175 I/Xposed  ( 9130): 【VCAM】onConfigured ：android.hardware.camera2.impl.CameraCaptureSessionImpl@44b1695
05-08 13:02:16.175 I/Xposed  ( 9130): 【VCAM】onConfigured ：android.hardware.camera2.impl.CameraCaptureSessionImpl@44b1695
05-08 13:02:16.175 I/Xposed  ( 9130): 【VCAM】onConfigured ：android.hardware.camera2.impl.CameraCaptureSessionImpl@44b1695
05-08 13:02:16.175 I/Xposed  ( 9130): 【VCAM】onConfigured ：android.hardware.camera2.impl.CameraCaptureSessionImpl@44b1695
05-08 13:02:16.175 I/Xposed  ( 9130): 【VCAM】onConfigured ：android.hardware.camera2.impl.CameraCaptureSessionImpl@44b1695
05-08 13:02:16.175 I/Xposed  ( 9130): 【VCAM】onConfigured ：android.hardware.camera2.impl.CameraCaptureSessionImpl@44b1695
05-08 13:02:16.175 I/Xposed  ( 9130): 【VCAM】onConfigured ：android.hardware.camera2.impl.CameraCaptureSessionImpl@44b1695
05-08 13:02:16.175 I/Xposed  ( 9130): 【VCAM】onConfigured ：android.hardware.camera2.impl.CameraCaptureSessionImpl@44b1695
05-08 13:02:16.175 I/Xposed  ( 9130): 【VCAM】onConfigured ：android.hardware.camera2.impl.CameraCaptureSessionImpl@44b1695
05-08 13:02:16.175 I/Xposed  ( 9130): 【VCAM】onConfigured ：android.hardware.camera2.impl.CameraCaptureSessionImpl@44b1695
05-08 13:02:16.175 I/Xposed  ( 9130): 【VCAM】onConfigured ：android.hardware.camera2.impl.CameraCaptureSessionImpl@44b1695
05-08 13:02:16.175 I/Xposed  ( 9130): 【VCAM】onConfigured ：android.hardware.camera2.impl.CameraCaptureSessionImpl@44b1695
05-08 13:02:16.175 I/Xposed  ( 9130): 【VCAM】onConfigured ：android.hardware.camera2.impl.CameraCaptureSessionImpl@44b1695
05-08 13:02:16.175 I/Xposed  ( 9130): 【VCAM】onConfigured ：android.hardware.camera2.impl.CameraCaptureSessionImpl@44b1695
05-08 13:02:16.183 I/Xposed  ( 9130): 【VCAM】开始build请求
05-08 13:02:16.184 I/Xposed  ( 9130): 【VCAM】Camera2处理过程完全执行
05-08 13:02:16.192 I/Xposed  ( 9130): 【VCAM】【decoder】开始解码
05-08 13:02:16.306 I/Xposed  ( 9130): 【VCAM】创建预览
05-08 13:02:16.308 I/Xposed  ( 9130): 【VCAM】【decoder】set decode color format to type 2135033992
05-08 13:02:16.342 I/Xposed  ( 9130): 【VCAM】开始预览
05-08 13:02:16.566 I/Xposed  ( 9130): 【VCAM】onConfigured ：android.hardware.camera2.impl.CameraCaptureSessionImpl@7f70749
05-08 13:02:16.566 I/Xposed  ( 9130): 【VCAM】onConfigured ：android.hardware.camera2.impl.CameraCaptureSessionImpl@7f70749
05-08 13:02:16.566 I/Xposed  ( 9130): 【VCAM】onConfigured ：android.hardware.camera2.impl.CameraCaptureSessionImpl@7f70749
05-08 13:02:16.566 I/Xposed  ( 9130): 【VCAM】onConfigured ：android.hardware.camera2.impl.CameraCaptureSessionImpl@7f70749
05-08 13:02:16.566 I/Xposed  ( 9130): 【VCAM】onConfigured ：android.hardware.camera2.impl.CameraCaptureSessionImpl@7f70749
05-08 13:02:16.567 I/Xposed  ( 9130): 【VCAM】onConfigured ：android.hardware.camera2.impl.CameraCaptureSessionImpl@7f70749
05-08 13:02:16.567 I/Xposed  ( 9130): 【VCAM】onConfigured ：android.hardware.camera2.impl.CameraCaptureSessionImpl@7f70749
05-08 13:02:16.567 I/Xposed  ( 9130): 【VCAM】onConfigured ：android.hardware.camera2.impl.CameraCaptureSessionImpl@7f70749
05-08 13:02:16.571 I/Xposed  ( 9130): 【VCAM】onConfigured ：android.hardware.camera2.impl.CameraCaptureSessionImpl@7f70749
05-08 13:02:16.572 I/Xposed  ( 9130): 【VCAM】onConfigured ：android.hardware.camera2.impl.CameraCaptureSessionImpl@7f70749
05-08 13:02:16.572 I/Xposed  ( 9130): 【VCAM】onConfigured ：android.hardware.camera2.impl.CameraCaptureSessionImpl@7f70749
05-08 13:02:16.572 I/Xposed  ( 9130): 【VCAM】onConfigured ：android.hardware.camera2.impl.CameraCaptureSessionImpl@7f70749
05-08 13:02:16.572 I/Xposed  ( 9130): 【VCAM】onConfigured ：android.hardware.camera2.impl.CameraCaptureSessionImpl@7f70749
05-08 13:02:16.572 I/Xposed  ( 9130): 【VCAM】onConfigured ：android.hardware.camera2.impl.CameraCaptureSessionImpl@7f70749
05-08 13:02:16.572 I/Xposed  ( 9130): 【VCAM】onConfigured ：android.hardware.camera2.impl.CameraCaptureSessionImpl@7f70749
05-08 13:02:16.572 I/Xposed  ( 9130): 【VCAM】onConfigured ：android.hardware.camera2.impl.CameraCaptureSessionImpl@7f70749
05-08 13:02:16.572 I/Xposed  ( 9130): 【VCAM】onConfigured ：android.hardware.camera2.impl.CameraCaptureSessionImpl@7f70749
05-08 13:02:16.572 I/Xposed  ( 9130): 【VCAM】onConfigured ：android.hardware.camera2.impl.CameraCaptureSessionImpl@7f70749
05-08 13:02:16.572 I/Xposed  ( 9130): 【VCAM】onConfigured ：android.hardware.camera2.impl.CameraCaptureSessionImpl@7f70749
05-08 13:02:16.572 I/Xposed  ( 9130): 【VCAM】onConfigured ：android.hardware.camera2.impl.CameraCaptureSessionImpl@7f70749
05-08 13:02:16.572 I/Xposed  ( 9130): 【VCAM】onConfigured ：android.hardware.camera2.impl.CameraCaptureSessionImpl@7f70749
05-08 13:02:16.572 I/Xposed  ( 9130): 【VCAM】onConfigured ：android.hardware.camera2.impl.CameraCaptureSessionImpl@7f70749
05-08 13:02:16.572 I/Xposed  ( 9130): 【VCAM】onConfigured ：android.hardware.camera2.impl.CameraCaptureSessionImpl@7f70749
05-08 13:02:16.572 I/Xposed  ( 9130): 【VCAM】onConfigured ：android.hardware.camera2.impl.CameraCaptureSessionImpl@7f70749
05-08 13:02:16.572 I/Xposed  ( 9130): 【VCAM】onConfigured ：android.hardware.camera2.impl.CameraCaptureSessionImpl@7f70749
05-08 13:02:16.572 I/Xposed  ( 9130): 【VCAM】onConfigured ：android.hardware.camera2.impl.CameraCaptureSessionImpl@7f70749
05-08 13:02:16.572 I/Xposed  ( 9130): 【VCAM】onConfigured ：android.hardware.camera2.impl.CameraCaptureSessionImpl@7f70749
05-08 13:02:16.572 I/Xposed  ( 9130): 【VCAM】onConfigured ：android.hardware.camera2.impl.CameraCaptureSessionImpl@7f70749
05-08 13:02:16.572 I/Xposed  ( 9130): 【VCAM】onConfigured ：android.hardware.camera2.impl.CameraCaptureSessionImpl@7f70749
05-08 13:02:16.572 I/Xposed  ( 9130): 【VCAM】onConfigured ：android.hardware.camera2.impl.CameraCaptureSessionImpl@7f70749
05-08 13:02:16.572 I/Xposed  ( 9130): 【VCAM】onConfigured ：android.hardware.camera2.impl.CameraCaptureSessionImpl@7f70749
05-08 13:02:16.572 I/Xposed  ( 9130): 【VCAM】onConfigured ：android.hardware.camera2.impl.CameraCaptureSessionImpl@7f70749
05-08 13:02:16.572 I/Xposed  ( 9130): 【VCAM】onConfigured ：android.hardware.camera2.impl.CameraCaptureSessionImpl@7f70749
05-08 13:02:16.572 I/Xposed  ( 9130): 【VCAM】onConfigured ：android.hardware.camera2.impl.CameraCaptureSessionImpl@7f70749
05-08 13:02:16.590 I/Xposed  ( 9130): 【VCAM】相机断开onDisconnected ：
05-08 13:02:16.590 I/Xposed  ( 9130): 【VCAM】相机断开onDisconnected ：
05-08 13:02:16.590 I/Xposed  ( 9130): 【VCAM】相机断开onDisconnected ：
05-08 13:02:16.605 I/Xposed  ( 9130): 【VCAM】[videofile]java.lang.IllegalStateException
05-08 13:02:16.788 I/Xposed  ( 9130): 【VCAM】帧预览回调初始化：宽：1280 高：720 帧率：30
05-08 13:02:16.802 I/Xposed  ( 9130): 【VCAM】【decoder】开始解码
05-08 13:02:17.026 I/Xposed  ( 9130): 【VCAM】【decoder】set decode color format to type 2135033992
05-08 13:02:57.409 I/Xposed  ( 9130): 【VCAM】创建预览
05-08 13:02:57.441 I/Xposed  ( 9130): 【VCAM】开始预览
05-08 13:02:57.907 I/Xposed  ( 9130): 【VCAM】帧预览回调初始化：宽：1280 高：720 帧率：30
05-08 13:02:57.917 I/Xposed  ( 9130): 【VCAM】【decoder】开始解码
05-08 13:02:58.148 I/Xposed  ( 9130): 【VCAM】【decoder】set decode color format to type 2135033992
05-08 13:03:00.400 I/Xposed  ( 9130): 【VCAM】创建预览
05-08 13:03:00.460 I/Xposed  ( 9130): 【VCAM】开始预览
05-08 13:03:01.195 I/Xposed  ( 9130): 【VCAM】创建预览
05-08 13:03:01.243 I/Xposed  ( 9130): 【VCAM】开始预览
05-08 13:03:01.633 I/Xposed  ( 9130): 【VCAM】帧预览回调初始化：宽：1280 高：720 帧率：30
05-08 13:03:01.678 I/Xposed  ( 9130): 【VCAM】【decoder】开始解码
05-08 13:03:01.842 I/Xposed  ( 9130): 【VCAM】【decoder】set decode color format to type 2135033992
05-08 13:03:06.125 I/Xposed  ( 9130): 【VCAM】创建预览
05-08 13:03:06.160 I/Xposed  ( 9130): 【VCAM】开始预览
05-08 13:03:07.183 I/Xposed  ( 9130): 【VCAM】创建预览
05-08 13:03:07.217 I/Xposed  ( 9130): 【VCAM】开始预览

**Comment by vistal8** [comment]
自己解决了   VidCoder-7.14 转换25xx*1464 的就可以了
