### ISSUE TITLE
绿屏或者花屏

### ISSUE THREAD

**Issue by vistal8** [w2016561536/android_virtual_cam#109]
创建了 应用创建了视频为：宽：1280 高：720格式35 绿屏 切换前后都是绿屏
创建了视频为：宽：2592 高：1458 绿屏 切换前后都是绿屏
以下是日志

05-15 04:09:53.647 I/Xposed  ( 4170): 【VCAM】打开相机C2
05-15 04:09:53.660 I/Xposed  ( 4170): 【VCAM】【重建垃圾场】Surface(name=android.graphics.SurfaceTexture@75f1a5a)/@0x921d48b
05-15 04:09:53.660 I/Xposed  ( 4170): 【VCAM】打开相机C2
05-15 04:09:53.686 I/Xposed  ( 4170): 【VCAM】应用创建了渲染器：宽：1280 高：720格式35
05-15 04:09:53.752 I/Xposed  ( 4170): 【VCAM】应用创建了渲染器：宽：2592 高：1458格式256
05-15 04:09:53.792 I/Xposed  ( 4170): 【VCAM】添加目标：Surface(name=null)/@0x5878929
05-15 04:09:53.798 I/Xposed  ( 4170): 【VCAM】createCaptureSession创捷捕获，原始:[Surface(name=null)/@0x5878929, Surface(name=null)/@0x53614ae]虚拟：Surface(name=android.graphics.SurfaceTexture@75f1a5a)/@0x921d48b
05-15 04:09:53.810 E/Xposed  ( 4170): java.lang.NoSuchMethodError: com.xunmeng.pdd_av_foundation.androidcamera.o0.a.k$b#onClosed(android.hardware.camera2.CameraCaptureSession)#exact
05-15 04:09:53.810 E/Xposed  ( 4170): 	at de.robv.android.xposed.XposedHelpers.findMethodExact(XposedHelpers.java:331)
05-15 04:09:53.810 E/Xposed  ( 4170): 	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:183)
05-15 04:09:53.810 E/Xposed  ( 4170): 	at com.example.vcam.HookMain.process_camera2Session_callback(HookMain.java:1176)
05-15 04:09:53.810 E/Xposed  ( 4170): 	at com.example.vcam.HookMain.access$600(HookMain.java:43)
05-15 04:09:53.810 E/Xposed  ( 4170): 	at com.example.vcam.HookMain$20$1.beforeHookedMethod(HookMain.java:867)
05-15 04:09:53.810 E/Xposed  ( 4170): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:344)
05-15 04:09:53.810 E/Xposed  ( 4170): 	at android.hardware.camera2.impl.CameraDeviceImpl.createCaptureSession(<Xposed>)
05-15 04:09:53.810 E/Xposed  ( 4170): 	at com.xunmeng.pdd_av_foundation.androidcamera.o0.a.k.g0(Camera2Impl.java:29)
05-15 04:09:53.810 E/Xposed  ( 4170): 	at com.xunmeng.pdd_av_foundation.androidcamera.o0.a.k$a.onOpened(Camera2Impl.java:3)
05-15 04:09:53.810 E/Xposed  ( 4170): 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
05-15 04:09:53.810 E/Xposed  ( 4170): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:364)
05-15 04:09:53.810 E/Xposed  ( 4170): 	at com.xunmeng.pdd_av_foundation.androidcamera.o0.a.k$a.onOpened(<Xposed>)
05-15 04:09:53.810 E/Xposed  ( 4170): 	at android.hardware.camera2.impl.CameraDeviceImpl$1.run(CameraDeviceImpl.java)
05-15 04:09:53.810 E/Xposed  ( 4170): 	at android.os.Handler.handleCallback(Handler.java)
05-15 04:09:53.810 E/Xposed  ( 4170): 	at android.os.Handler.dispatchMessage(Handler.java)
05-15 04:09:53.810 E/Xposed  ( 4170): 	at com.xunmeng.pinduoduo.threadpool.i$d.dispatchMessage(PddHandler.java:3)
05-15 04:09:53.810 E/Xposed  ( 4170): 	at android.os.Looper.loop(Looper.java)
05-15 04:09:53.810 E/Xposed  ( 4170): 	at android.os.HandlerThread.run(HandlerThread.java)
05-15 04:09:53.810 I/Xposed  ( 4170): 【VCAM】createCaptureSession创捷捕获，原始:[Surface(name=android.graphics.SurfaceTexture@75f1a5a)/@0x921d48b]虚拟：Surface(name=android.graphics.SurfaceTexture@75f1a5a)/@0x921d48b
05-15 04:09:53.816 E/Xposed  ( 4170): java.lang.NoSuchMethodError: com.xunmeng.pdd_av_foundation.androidcamera.o0.a.k$b#onClosed(android.hardware.camera2.CameraCaptureSession)#exact
05-15 04:09:53.816 E/Xposed  ( 4170): 	at de.robv.android.xposed.XposedHelpers.findMethodExact(XposedHelpers.java:331)
05-15 04:09:53.816 E/Xposed  ( 4170): 	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:183)
05-15 04:09:53.816 E/Xposed  ( 4170): 	at com.example.vcam.HookMain.process_camera2Session_callback(HookMain.java:1176)
05-15 04:09:53.816 E/Xposed  ( 4170): 	at com.example.vcam.HookMain.access$600(HookMain.java:43)
05-15 04:09:53.816 E/Xposed  ( 4170): 	at com.example.vcam.HookMain$20$1.beforeHookedMethod(HookMain.java:867)
05-15 04:09:53.816 E/Xposed  ( 4170): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:344)
05-15 04:09:53.816 E/Xposed  ( 4170): 	at android.hardware.camera2.impl.CameraDeviceImpl.createCaptureSession(<Xposed>)
05-15 04:09:53.816 E/Xposed  ( 4170): 	at com.xunmeng.pdd_av_foundation.androidcamera.o0.a.k.g0(Camera2Impl.java:29)
05-15 04:09:53.816 E/Xposed  ( 4170): 	at com.xunmeng.pdd_av_foundation.androidcamera.o0.a.k$a.onOpened(Camera2Impl.java:3)
05-15 04:09:53.816 E/Xposed  ( 4170): 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
05-15 04:09:53.816 E/Xposed  ( 4170): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:364)
05-15 04:09:53.816 E/Xposed  ( 4170): 	at com.xunmeng.pdd_av_foundation.androidcamera.o0.a.k$a.onOpened(<Xposed>)
05-15 04:09:53.816 E/Xposed  ( 4170): 	at android.hardware.camera2.impl.CameraDeviceImpl$1.run(CameraDeviceImpl.java)
05-15 04:09:53.816 E/Xposed  ( 4170): 	at android.os.Handler.handleCallback(Handler.java)
05-15 04:09:53.816 E/Xposed  ( 4170): 	at android.os.Handler.dispatchMessage(Handler.java)
05-15 04:09:53.816 E/Xposed  ( 4170): 	at com.xunmeng.pinduoduo.threadpool.i$d.dispatchMessage(PddHandler.java:3)
05-15 04:09:53.816 E/Xposed  ( 4170): 	at android.os.Looper.loop(Looper.java)
05-15 04:09:53.816 E/Xposed  ( 4170): 	at android.os.HandlerThread.run(HandlerThread.java)
05-15 04:09:53.816 I/Xposed  ( 4170): 【VCAM】createCaptureSession创捷捕获，原始:[Surface(name=android.graphics.SurfaceTexture@75f1a5a)/@0x921d48b]虚拟：Surface(name=android.graphics.SurfaceTexture@75f1a5a)/@0x921d48b
05-15 04:09:53.817 E/Xposed  ( 4170): java.lang.NoSuchMethodError: com.xunmeng.pdd_av_foundation.androidcamera.o0.a.k$b#onClosed(android.hardware.camera2.CameraCaptureSession)#exact
05-15 04:09:53.817 E/Xposed  ( 4170): 	at de.robv.android.xposed.XposedHelpers.findMethodExact(XposedHelpers.java:331)
05-15 04:09:53.817 E/Xposed  ( 4170): 	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:183)
05-15 04:09:53.817 E/Xposed  ( 4170): 	at com.example.vcam.HookMain.process_camera2Session_callback(HookMain.java:1176)
05-15 04:09:53.817 E/Xposed  ( 4170): 	at com.example.vcam.HookMain.access$600(HookMain.java:43)
05-15 04:09:53.817 E/Xposed  ( 4170): 	at com.example.vcam.HookMain$20$1.beforeHookedMethod(HookMain.java:867)
05-15 04:09:53.817 E/Xposed  ( 4170): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:344)
05-15 04:09:53.817 E/Xposed  ( 4170): 	at android.hardware.camera2.impl.CameraDeviceImpl.createCaptureSession(<Xposed>)
05-15 04:09:53.817 E/Xposed  ( 4170): 	at com.xunmeng.pdd_av_foundation.androidcamera.o0.a.k.g0(Camera2Impl.java:29)
05-15 04:09:53.817 E/Xposed  ( 4170): 	at com.xunmeng.pdd_av_foundation.androidcamera.o0.a.k$a.onOpened(Camera2Impl.java:3)
05-15 04:09:53.817 E/Xposed  ( 4170): 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
05-15 04:09:53.817 E/Xposed  ( 4170): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:364)
05-15 04:09:53.817 E/Xposed  ( 4170): 	at com.xunmeng.pdd_av_foundation.androidcamera.o0.a.k$a.onOpened(<Xposed>)
05-15 04:09:53.817 E/Xposed  ( 4170): 	at android.hardware.camera2.impl.CameraDeviceImpl$1.run(CameraDeviceImpl.java)
05-15 04:09:53.817 E/Xposed  ( 4170): 	at android.os.Handler.handleCallback(Handler.java)
05-15 04:09:53.817 E/Xposed  ( 4170): 	at android.os.Handler.dispatchMessage(Handler.java)
05-15 04:09:53.817 E/Xposed  ( 4170): 	at com.xunmeng.pinduoduo.threadpool.i$d.dispatchMessage(PddHandler.java:3)
05-15 04:09:53.817 E/Xposed  ( 4170): 	at android.os.Looper.loop(Looper.java)
05-15 04:09:53.817 E/Xposed  ( 4170): 	at android.os.HandlerThread.run(HandlerThread.java)
05-15 04:09:53.817 I/Xposed  ( 4170): 【VCAM】createCaptureSession创捷捕获，原始:[Surface(name=android.graphics.SurfaceTexture@75f1a5a)/@0x921d48b]虚拟：Surface(name=android.graphics.SurfaceTexture@75f1a5a)/@0x921d48b
05-15 04:09:53.821 E/Xposed  ( 4170): java.lang.NoSuchMethodError: com.xunmeng.pdd_av_foundation.androidcamera.o0.a.k$b#onClosed(android.hardware.camera2.CameraCaptureSession)#exact
05-15 04:09:53.821 E/Xposed  ( 4170): 	at de.robv.android.xposed.XposedHelpers.findMethodExact(XposedHelpers.java:331)
05-15 04:09:53.821 E/Xposed  ( 4170): 	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:183)
05-15 04:09:53.821 E/Xposed  ( 4170): 	at com.example.vcam.HookMain.process_camera2Session_callback(HookMain.java:1176)
05-15 04:09:53.821 E/Xposed  ( 4170): 	at com.example.vcam.HookMain.access$600(HookMain.java:43)
05-15 04:09:53.821 E/Xposed  ( 4170): 	at com.example.vcam.HookMain$20$1.beforeHookedMethod(HookMain.java:867)
05-15 04:09:53.821 E/Xposed  ( 4170): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:344)
05-15 04:09:53.821 E/Xposed  ( 4170): 	at android.hardware.camera2.impl.CameraDeviceImpl.createCaptureSession(<Xposed>)
05-15 04:09:53.821 E/Xposed  ( 4170): 	at com.xunmeng.pdd_av_foundation.androidcamera.o0.a.k.g0(Camera2Impl.java:29)
05-15 04:09:53.821 E/Xposed  ( 4170): 	at com.xunmeng.pdd_av_foundation.androidcamera.o0.a.k$a.onOpened(Camera2Impl.java:3)
05-15 04:09:53.821 E/Xposed  ( 4170): 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
05-15 04:09:53.821 E/Xposed  ( 4170): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:364)
05-15 04:09:53.821 E/Xposed  ( 4170): 	at com.xunmeng.pdd_av_foundation.androidcamera.o0.a.k$a.onOpened(<Xposed>)
05-15 04:09:53.821 E/Xposed  ( 4170): 	at android.hardware.camera2.impl.CameraDeviceImpl$1.run(CameraDeviceImpl.java)
05-15 04:09:53.821 E/Xposed  ( 4170): 	at android.os.Handler.handleCallback(Handler.java)
05-15 04:09:53.821 E/Xposed  ( 4170): 	at android.os.Handler.dispatchMessage(Handler.java)
05-15 04:09:53.821 E/Xposed  ( 4170): 	at com.xunmeng.pinduoduo.threadpool.i$d.dispatchMessage(PddHandler.java:3)
05-15 04:09:53.821 E/Xposed  ( 4170): 	at android.os.Looper.loop(Looper.java)
05-15 04:09:53.821 E/Xposed  ( 4170): 	at android.os.HandlerThread.run(HandlerThread.java)
05-15 04:09:53.821 I/Xposed  ( 4170): 【VCAM】createCaptureSession创捷捕获，原始:[Surface(name=android.graphics.SurfaceTexture@75f1a5a)/@0x921d48b]虚拟：Surface(name=android.graphics.SurfaceTexture@75f1a5a)/@0x921d48b
05-15 04:09:53.823 E/Xposed  ( 4170): java.lang.NoSuchMethodError: com.xunmeng.pdd_av_foundation.androidcamera.o0.a.k$b#onClosed(android.hardware.camera2.CameraCaptureSession)#exact
05-15 04:09:53.823 E/Xposed  ( 4170): 	at de.robv.android.xposed.XposedHelpers.findMethodExact(XposedHelpers.java:331)
05-15 04:09:53.823 E/Xposed  ( 4170): 	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:183)
05-15 04:09:53.823 E/Xposed  ( 4170): 	at com.example.vcam.HookMain.process_camera2Session_callback(HookMain.java:1176)
05-15 04:09:53.823 E/Xposed  ( 4170): 	at com.example.vcam.HookMain.access$600(HookMain.java:43)
05-15 04:09:53.823 E/Xposed  ( 4170): 	at com.example.vcam.HookMain$20$1.beforeHookedMethod(HookMain.java:867)
05-15 04:09:53.823 E/Xposed  ( 4170): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:344)
05-15 04:09:53.823 E/Xposed  ( 4170): 	at android.hardware.camera2.impl.CameraDeviceImpl.createCaptureSession(<Xposed>)
05-15 04:09:53.823 E/Xposed  ( 4170): 	at com.xunmeng.pdd_av_foundation.androidcamera.o0.a.k.g0(Camera2Impl.java:29)
05-15 04:09:53.823 E/Xposed  ( 4170): 	at com.xunmeng.pdd_av_foundation.androidcamera.o0.a.k$a.onOpened(Camera2Impl.java:3)
05-15 04:09:53.823 E/Xposed  ( 4170): 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
05-15 04:09:53.823 E/Xposed  ( 4170): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:364)
05-15 04:09:53.823 E/Xposed  ( 4170): 	at com.xunmeng.pdd_av_foundation.androidcamera.o0.a.k$a.onOpened(<Xposed>)
05-15 04:09:53.823 E/Xposed  ( 4170): 	at android.hardware.camera2.impl.CameraDeviceImpl$1.run(CameraDeviceImpl.java)
05-15 04:09:53.823 E/Xposed  ( 4170): 	at android.os.Handler.handleCallback(Handler.java)
05-15 04:09:53.823 E/Xposed  ( 4170): 	at android.os.Handler.dispatchMessage(Handler.java)
05-15 04:09:53.823 E/Xposed  ( 4170): 	at com.xunmeng.pinduoduo.threadpool.i$d.dispatchMessage(PddHandler.java:3)
05-15 04:09:53.823 E/Xposed  ( 4170): 	at android.os.Looper.loop(Looper.java)
05-15 04:09:53.823 E/Xposed  ( 4170): 	at android.os.HandlerThread.run(HandlerThread.java)
05-15 04:09:53.823 I/Xposed  ( 4170): 【VCAM】createCaptureSession创捷捕获，原始:[Surface(name=android.graphics.SurfaceTexture@75f1a5a)/@0x921d48b]虚拟：Surface(name=android.graphics.SurfaceTexture@75f1a5a)/@0x921d48b
05-15 04:09:53.827 E/Xposed  ( 4170): java.lang.NoSuchMethodError: com.xunmeng.pdd_av_foundation.androidcamera.o0.a.k$b#onClosed(android.hardware.camera2.CameraCaptureSession)#exact
05-15 04:09:53.827 E/Xposed  ( 4170): 	at de.robv.android.xposed.XposedHelpers.findMethodExact(XposedHelpers.java:331)
05-15 04:09:53.827 E/Xposed  ( 4170): 	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:183)
05-15 04:09:53.827 E/Xposed  ( 4170): 	at com.example.vcam.HookMain.process_camera2Session_callback(HookMain.java:1176)
05-15 04:09:53.827 E/Xposed  ( 4170): 	at com.example.vcam.HookMain.access$600(HookMain.java:43)
05-15 04:09:53.827 E/Xposed  ( 4170): 	at com.example.vcam.HookMain$20$1.beforeHookedMethod(HookMain.java:867)
05-15 04:09:53.827 E/Xposed  ( 4170): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:344)
05-15 04:09:53.827 E/Xposed  ( 4170): 	at android.hardware.camera2.impl.CameraDeviceImpl.createCaptureSession(<Xposed>)
05-15 04:09:53.827 E/Xposed  ( 4170): 	at com.xunmeng.pdd_av_foundation.androidcamera.o0.a.k.g0(Camera2Impl.java:29)
05-15 04:09:53.827 E/Xposed  ( 4170): 	at com.xunmeng.pdd_av_foundation.androidcamera.o0.a.k$a.onOpened(Camera2Impl.java:3)
05-15 04:09:53.827 E/Xposed  ( 4170): 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
05-15 04:09:53.827 E/Xposed  ( 4170): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:364)
05-15 04:09:53.827 E/Xposed  ( 4170): 	at com.xunmeng.pdd_av_foundation.androidcamera.o0.a.k$a.onOpened(<Xposed>)
05-15 04:09:53.827 E/Xposed  ( 4170): 	at android.hardware.camera2.impl.CameraDeviceImpl$1.run(CameraDeviceImpl.java)
05-15 04:09:53.827 E/Xposed  ( 4170): 	at android.os.Handler.handleCallback(Handler.java)
05-15 04:09:53.827 E/Xposed  ( 4170): 	at android.os.Handler.dispatchMessage(Handler.java)
05-15 04:09:53.827 E/Xposed  ( 4170): 	at com.xunmeng.pinduoduo.threadpool.i$d.dispatchMessage(PddHandler.java:3)
05-15 04:09:53.827 E/Xposed  ( 4170): 	at android.os.Looper.loop(Looper.java)
05-15 04:09:53.827 E/Xposed  ( 4170): 	at android.os.HandlerThread.run(HandlerThread.java)
05-15 04:09:53.827 I/Xposed  ( 4170): 【VCAM】createCaptureSession创捷捕获，原始:[Surface(name=android.graphics.SurfaceTexture@75f1a5a)/@0x921d48b]虚拟：Surface(name=android.graphics.SurfaceTexture@75f1a5a)/@0x921d48b
05-15 04:09:53.830 E/Xposed  ( 4170): java.lang.NoSuchMethodError: com.xunmeng.pdd_av_foundation.androidcamera.o0.a.k$b#onClosed(android.hardware.camera2.CameraCaptureSession)#exact
05-15 04:09:53.830 E/Xposed  ( 4170): 	at de.robv.android.xposed.XposedHelpers.findMethodExact(XposedHelpers.java:331)
05-15 04:09:53.830 E/Xposed  ( 4170): 	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:183)
05-15 04:09:53.830 E/Xposed  ( 4170): 	at com.example.vcam.HookMain.process_camera2Session_callback(HookMain.java:1176)
05-15 04:09:53.830 E/Xposed  ( 4170): 	at com.example.vcam.HookMain.access$600(HookMain.java:43)
05-15 04:09:53.830 E/Xposed  ( 4170): 	at com.example.vcam.HookMain$20$1.beforeHookedMethod(HookMain.java:867)
05-15 04:09:53.830 E/Xposed  ( 4170): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:344)
05-15 04:09:53.830 E/Xposed  ( 4170): 	at android.hardware.camera2.impl.CameraDeviceImpl.createCaptureSession(<Xposed>)
05-15 04:09:53.830 E/Xposed  ( 4170): 	at com.xunmeng.pdd_av_foundation.androidcamera.o0.a.k.g0(Camera2Impl.java:29)
05-15 04:09:53.830 E/Xposed  ( 4170): 	at com.xunmeng.pdd_av_foundation.androidcamera.o0.a.k$a.onOpened(Camera2Impl.java:3)
05-15 04:09:53.830 E/Xposed  ( 4170): 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
05-15 04:09:53.830 E/Xposed  ( 4170): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:364)
05-15 04:09:53.830 E/Xposed  ( 4170): 	at com.xunmeng.pdd_av_foundation.androidcamera.o0.a.k$a.onOpened(<Xposed>)
05-15 04:09:53.830 E/Xposed  ( 4170): 	at android.hardware.camera2.impl.CameraDeviceImpl$1.run(CameraDeviceImpl.java)
05-15 04:09:53.830 E/Xposed  ( 4170): 	at android.os.Handler.handleCallback(Handler.java)
05-15 04:09:53.830 E/Xposed  ( 4170): 	at android.os.Handler.dispatchMessage(Handler.java)
05-15 04:09:53.830 E/Xposed  ( 4170): 	at com.xunmeng.pinduoduo.threadpool.i$d.dispatchMessage(PddHandler.java:3)
05-15 04:09:53.830 E/Xposed  ( 4170): 	at android.os.Looper.loop(Looper.java)
05-15 04:09:53.830 E/Xposed  ( 4170): 	at android.os.HandlerThread.run(HandlerThread.java)
05-15 04:09:53.830 I/Xposed  ( 4170): 【VCAM】createCaptureSession创捷捕获，原始:[Surface(name=android.graphics.SurfaceTexture@75f1a5a)/@0x921d48b]虚拟：Surface(name=android.graphics.SurfaceTexture@75f1a5a)/@0x921d48b
05-15 04:09:53.832 E/Xposed  ( 4170): java.lang.NoSuchMethodError: com.xunmeng.pdd_av_foundation.androidcamera.o0.a.k$b#onClosed(android.hardware.camera2.CameraCaptureSession)#exact
05-15 04:09:53.832 E/Xposed  ( 4170): 	at de.robv.android.xposed.XposedHelpers.findMethodExact(XposedHelpers.java:331)
05-15 04:09:53.832 E/Xposed  ( 4170): 	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:183)
05-15 04:09:53.832 E/Xposed  ( 4170): 	at com.example.vcam.HookMain.process_camera2Session_callback(HookMain.java:1176)
05-15 04:09:53.832 E/Xposed  ( 4170): 	at com.example.vcam.HookMain.access$600(HookMain.java:43)
05-15 04:09:53.832 E/Xposed  ( 4170): 	at com.example.vcam.HookMain$20$1.beforeHookedMethod(HookMain.java:867)
05-15 04:09:53.832 E/Xposed  ( 4170): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:344)
05-15 04:09:53.832 E/Xposed  ( 4170): 	at android.hardware.camera2.impl.CameraDeviceImpl.createCaptureSession(<Xposed>)
05-15 04:09:53.832 E/Xposed  ( 4170): 	at com.xunmeng.pdd_av_foundation.androidcamera.o0.a.k.g0(Camera2Impl.java:29)
05-15 04:09:53.832 E/Xposed  ( 4170): 	at com.xunmeng.pdd_av_foundation.androidcamera.o0.a.k$a.onOpened(Camera2Impl.java:3)
05-15 04:09:53.832 E/Xposed  ( 4170): 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
05-15 04:09:53.832 E/Xposed  ( 4170): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:364)
05-15 04:09:53.832 E/Xposed  ( 4170): 	at com.xunmeng.pdd_av_foundation.androidcamera.o0.a.k$a.onOpened(<Xposed>)
05-15 04:09:53.832 E/Xposed  ( 4170): 	at android.hardware.camera2.impl.CameraDeviceImpl$1.run(CameraDeviceImpl.java)
05-15 04:09:53.832 E/Xposed  ( 4170): 	at android.os.Handler.handleCallback(Handler.java)
05-15 04:09:53.832 E/Xposed  ( 4170): 	at android.os.Handler.dispatchMessage(Handler.java)
05-15 04:09:53.832 E/Xposed  ( 4170): 	at com.xunmeng.pinduoduo.threadpool.i$d.dispatchMessage(PddHandler.java:3)
05-15 04:09:53.832 E/Xposed  ( 4170): 	at android.os.Looper.loop(Looper.java)
05-15 04:09:53.832 E/Xposed  ( 4170): 	at android.os.HandlerThread.run(HandlerThread.java)
05-15 04:09:53.832 I/Xposed  ( 4170): 【VCAM】createCaptureSession创捷捕获，原始:[Surface(name=android.graphics.SurfaceTexture@75f1a5a)/@0x921d48b]虚拟：Surface(name=android.graphics.SurfaceTexture@75f1a5a)/@0x921d48b
05-15 04:09:53.833 E/Xposed  ( 4170): java.lang.NoSuchMethodError: com.xunmeng.pdd_av_foundation.androidcamera.o0.a.k$b#onClosed(android.hardware.camera2.CameraCaptureSession)#exact
05-15 04:09:53.833 E/Xposed  ( 4170): 	at de.robv.android.xposed.XposedHelpers.findMethodExact(XposedHelpers.java:331)
05-15 04:09:53.833 E/Xposed  ( 4170): 	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:183)
05-15 04:09:53.833 E/Xposed  ( 4170): 	at com.example.vcam.HookMain.process_camera2Session_callback(HookMain.java:1176)
05-15 04:09:53.833 E/Xposed  ( 4170): 	at com.example.vcam.HookMain.access$600(HookMain.java:43)
05-15 04:09:53.833 E/Xposed  ( 4170): 	at com.example.vcam.HookMain$20$1.beforeHookedMethod(HookMain.java:867)
05-15 04:09:53.833 E/Xposed  ( 4170): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:344)
05-15 04:09:53.833 E/Xposed  ( 4170): 	at android.hardware.camera2.impl.CameraDeviceImpl.createCaptureSession(<Xposed>)
05-15 04:09:53.833 E/Xposed  ( 4170): 	at com.xunmeng.pdd_av_foundation.androidcamera.o0.a.k.g0(Camera2Impl.java:29)
05-15 04:09:53.833 E/Xposed  ( 4170): 	at com.xunmeng.pdd_av_foundation.androidcamera.o0.a.k$a.onOpened(Camera2Impl.java:3)
05-15 04:09:53.833 E/Xposed  ( 4170): 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
05-15 04:09:53.833 E/Xposed  ( 4170): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:364)
05-15 04:09:53.833 E/Xposed  ( 4170): 	at com.xunmeng.pdd_av_foundation.androidcamera.o0.a.k$a.onOpened(<Xposed>)
05-15 04:09:53.833 E/Xposed  ( 4170): 	at android.hardware.camera2.impl.CameraDeviceImpl$1.run(CameraDeviceImpl.java)
05-15 04:09:53.833 E/Xposed  ( 4170): 	at android.os.Handler.handleCallback(Handler.java)
05-15 04:09:53.833 E/Xposed  ( 4170): 	at android.os.Handler.dispatchMessage(Handler.java)
05-15 04:09:53.833 E/Xposed  ( 4170): 	at com.xunmeng.pinduoduo.threadpool.i$d.dispatchMessage(PddHandler.java:3)
05-15 04:09:53.833 E/Xposed  ( 4170): 	at android.os.Looper.loop(Looper.java)
05-15 04:09:53.833 E/Xposed  ( 4170): 	at android.os.HandlerThread.run(HandlerThread.java)
05-15 04:09:53.840 I/Xposed  ( 4170): 【VCAM】相机断开onDisconnected ：
05-15 04:09:53.840 I/Xposed  ( 4170): 【VCAM】相机断开onDisconnected ：
05-15 04:09:53.840 I/Xposed  ( 4170): 【VCAM】相机断开onDisconnected ：
05-15 04:09:53.860 I/Xposed  ( 4170): 【VCAM】【重建垃圾场】Surface(name=android.graphics.SurfaceTexture@77efd10)/@0xc8cd009
05-15 04:09:53.860 I/Xposed  ( 4170): 【VCAM】打开相机C2
05-15 04:09:53.865 I/Xposed  ( 4170): 【VCAM】【重建垃圾场】Surface(name=android.graphics.SurfaceTexture@484844b)/@0x9bd5e28
05-15 04:09:53.866 I/Xposed  ( 4170): 【VCAM】打开相机C2
05-15 04:09:53.874 I/Xposed  ( 4170): 【VCAM】【重建垃圾场】Surface(name=android.graphics.SurfaceTexture@8af4972)/@0xb2f31c3
05-15 04:09:53.874 I/Xposed  ( 4170): 【VCAM】打开相机C2
05-15 04:09:53.879 I/Xposed  ( 4170): 【VCAM】应用创建了渲染器：宽：1280 高：720格式35
05-15 04:09:53.896 I/Xposed  ( 4170): 【VCAM】应用创建了渲染器：宽：2592 高：1458格式256

**Comment by liujiaqi7998** [comment]
在某会议软件上会出现此类问题，经过日志排查，该软件运行一段时间后会莫名其妙改变分辨率，从size: 1280x720改成size: 640x360导致解析的视频分辨率和输出分辨率不吻合造成花屏。

**Comment by IQyo** [comment]
@liujiaqi7998  所以这个问题目前有办法解决吗,或者有其他APP可以用吗,

**Comment by liujiaqi7998** [comment]
读取正确的分辨率，进行渲染
