### ISSUE TITLE
application force closes after pressing to get a photo from "virtual.mp4"

### ISSUE THREAD

**Issue by kalawy** [w2016561536/android_virtual_cam#135]
video gets played  normally in  live feed, but when trying to capture a photo from that video .. the application force closes 

crash report : 
FATAL EXCEPTION: main
java.lang.UnsupportedOperationException: The producer output buffer format 0x7fa30c04 doesn't match the ImageReader's configured buffer format 0x21.
	at android.media.ImageReader.nativeImageSetup(Native Method)
	at android.media.ImageReader.acquireNextSurfaceImage(ImageReader.java:568)
	at android.media.ImageReader.acquireNextImage(ImageReader.java:627)
	at androidx.camera.core.AndroidImageReaderProxy.acquireNextImage(AndroidImageReaderProxy.java:81)
	at androidx.camera.core.MetadataImageReader.imageIncoming(MetadataImageReader.java:322)
	at androidx.camera.core.MetadataImageReader.lambda$new$0$MetadataImageReader(MetadataImageReader.java:65)
	at androidx.camera.core.-$$Lambda$MetadataImageReader$5BCjqfsC6khPZYU3ar10sNremNk.onImageAvailable(Unknown Source:2)
	at androidx.camera.core.AndroidImageReaderProxy.lambda$setOnImageAvailableListener$0$AndroidImageReaderProxy(AndroidImageReaderProxy.java:141)
	at androidx.camera.core.-$$Lambda$AndroidImageReaderProxy$ydxkGVJ03P0ZMYkq3dfSV-hzi3E.run(Unknown Source:4)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8741)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

**Comment by kenlam5551** [comment]
same problem, hope someone help to slove it

**Comment by bacevs** [comment]
Same issue. The camera viewer is correctly showing my virtual.mp4 but as soon as a click the button to take a photo Costco app is crashing. 

1000.bmp not working, so I created video at the shown dimensions 480x720

![Screenshot_20221217-052401](https://user-images.githubusercontent.com/1433845/208164862-a30813e6-61d7-45a2-808b-b0254fefab05.png)
![Screenshot_20221217-053033](https://user-images.githubusercontent.com/1433845/208165416-cea8db87-6f33-4e8c-a69c-6fcd3bd274ae.png)
![Screenshot_20221217-053522](https://user-images.githubusercontent.com/1433845/208165955-536d46bb-3cbb-489d-9325-3cb41f57f289.png)




Edit: So I tried doing a Facebook Messenger call to see what the other person would see, this is what they saw from me being shown on video call:
![received_1222597135134295](https://user-images.githubusercontent.com/1433845/208169310-99b61ebc-624c-49b4-ad2b-70e732575e5c.jpeg)

My virtual video is correctly showing on my phone however in the top right hand corner:
![Screenshot_20221217-055800](https://user-images.githubusercontent.com/1433845/208169777-fe96bade-10dc-438f-8112-9f93de45ee7a.png)

**Comment by matthewkram419** [comment]
same shit
