### ISSUE TITLE
进入之后视频预览正常 但按钮点不动 付费求解决

### ISSUE THREAD

**Issue by fuckgithubh** [w2016561536/android_virtual_cam#166]
----part 5 start----
[ 2023-04-27T18:37:36.161    10251: 25369: 25369 I/LSPosed         ] Loading xposed for com.ms.ailiao/10251
[ 2023-04-27T18:37:36.179    10251: 25369: 25369 I/LSPosed-Bridge  ] Loading module com.example.vcam from /data/app/~~UvsJYjNY5_wxeoc1h8sDgw==/com.example.vcam-DizwhPs4QKHNC9Hp4dJHoQ==/base.apk
[ 2023-04-27T18:37:36.179    10251: 25369: 25369 I/LSPosed-Bridge  ]   Loading class com.example.vcam.HookMain
[ 2023-04-27T18:37:36.470    10251: 25409: 25409 I/LSPosed         ] Loading xposed for com.ms.ailiao:core/10251
[ 2023-04-27T18:37:36.492    10251: 25409: 25409 I/LSPosed-Bridge  ] Loading module com.example.vcam from /data/app/~~UvsJYjNY5_wxeoc1h8sDgw==/com.example.vcam-DizwhPs4QKHNC9Hp4dJHoQ==/base.apk
[ 2023-04-27T18:37:36.493    10251: 25409: 25409 I/LSPosed-Bridge  ]   Loading class com.example.vcam.HookMain
[ 2023-04-27T18:37:41.423    10251: 25369: 25848 I/LSPosed-Bridge  ] 【VCAM】1位参数初始化相机，类：class com.camerakit.d.h.a$e$a
[ 2023-04-27T18:37:41.442    10251: 25369: 25848 I/LSPosed-Bridge  ] 【VCAM】【重建垃圾场】Surface(name=android.graphics.SurfaceTexture@eee3b32)/@0xc24a083
[ 2023-04-27T18:37:41.442    10251: 25369: 25848 I/LSPosed-Bridge  ] 【VCAM】打开相机C2
[ 2023-04-27T18:37:41.450    10251: 25369: 25849 I/LSPosed-Bridge  ] 【VCAM】应用创建了渲染器：宽：1920 高：1080格式256
[ 2023-04-27T18:37:41.452    10251: 25369: 25849 I/LSPosed-Bridge  ] 【VCAM】[toast]java.lang.NullPointerException: Can't toast on a thread that has not called Looper.prepare()
[ 2023-04-27T18:37:41.452    10251: 25369: 25849 I/LSPosed-Bridge  ] 【VCAM】应用创建了渲染器：宽：1920 高：1080格式256
[ 2023-04-27T18:37:41.454    10251: 25369: 25849 I/LSPosed-Bridge  ] 【VCAM】[toast]java.lang.NullPointerException: Can't toast on a thread that has not called Looper.prepare()
[ 2023-04-27T18:37:41.454    10251: 25369: 25849 I/LSPosed-Bridge  ] 【VCAM】应用创建了渲染器：宽：1920 高：1080格式256
[ 2023-04-27T18:37:41.456    10251: 25369: 25849 I/LSPosed-Bridge  ] 【VCAM】[toast]java.lang.NullPointerException: Can't toast on a thread that has not called Looper.prepare()
[ 2023-04-27T18:37:41.456    10251: 25369: 25849 I/LSPosed-Bridge  ] 【VCAM】应用创建了渲染器：宽：1920 高：1080格式256
[ 2023-04-27T18:37:41.456    10251: 25369: 25849 I/LSPosed-Bridge  ] 【VCAM】[toast]java.lang.NullPointerException: Can't toast on a thread that has not called Looper.prepare()
[ 2023-04-27T18:37:41.457    10251: 25369: 25849 I/LSPosed-Bridge  ] 【VCAM】createCaptureSession创捷捕获，原始:[Surface(name=com.camerakit.preview.CameraSurfaceTexture@4ed38f4)/@0x113c81d, Surface(name=null)/@0xfd33a92]虚拟：Surface(name=android.graphics.SurfaceTexture@eee3b32)/@0xc24a083
[ 2023-04-27T18:37:41.524    10251: 25369: 25848 I/LSPosed-Bridge  ] 【VCAM】onConfigured ：android.hardware.camera2.impl.CameraCaptureSessionImpl@71ef060
[ 2023-04-27T18:37:41.526    10251: 25369: 25848 I/LSPosed-Bridge  ] 【VCAM】添加目标：Surface(name=com.camerakit.preview.CameraSurfaceTexture@4ed38f4)/@0x113c81d
[ 2023-04-27T18:37:41.529    10251: 25369: 25848 I/LSPosed-Bridge  ] 【VCAM】开始build请求
[ 2023-04-27T18:37:41.543    10251: 25369: 25848 I/LSPosed-Bridge  ] 【VCAM】Camera2处理过程完全执行
[ 2023-04-27T18:37:42.251    10251: 25369: 25849 I/LSPosed-Bridge  ] 【VCAM】添加目标：Surface(name=null)/@0xfd33a92
[ 2023-04-27T18:37:42.263    10251: 25369: 25848 I/LSPosed-Bridge  ] 【VCAM】开始build请求
[ 2023-04-27T18:37:42.266    10251: 25369: 25891 I/LSPosed-Bridge  ] 【VCAM】【decoder】开始解码
[ 2023-04-27T18:37:42.319    10251: 25369: 25891 I/LSPosed-Bridge  ] 【VCAM】【decoder】set decode color format to type 2135033992
[ 2023-04-27T18:37:42.334    10251: 25369: 25848 I/LSPosed-Bridge  ] 【VCAM】Camera2处理过程完全执行
[ 2023-04-27T18:37:42.537    10251: 25369: 25848 I/LSPosed-Bridge  ] 【VCAM】开始build请求
[ 2023-04-27T18:37:42.538    10251: 25369: 25914 I/LSPosed-Bridge  ] 【VCAM】【decoder】开始解码
[ 2023-04-27T18:37:42.584    10251: 25369: 25914 I/LSPosed-Bridge  ] 【VCAM】【decoder】set decode color format to type 2135033992
[ 2023-04-27T18:37:42.595    10251: 25369: 25848 I/LSPosed-Bridge  ] 【VCAM】Camera2处理过程完全执行
[ 2023-04-27T18:37:42.830    10251: 25369: 25848 I/LSPosed-Bridge  ] Crash unexpectedly: java.lang.UnsupportedOperationException: The producer output buffer format 0x7fa30c04 doesn't match the ImageReader's configured buffer format 0x21.
	at android.media.ImageReader.nativeImageSetup(Native Method)
	at android.media.ImageReader.acquireNextSurfaceImage(ImageReader.java:465)
	at android.media.ImageReader.acquireNextImage(ImageReader.java:519)
	at android.media.ImageReader.acquireLatestImage(ImageReader.java:412)
	at com.camerakit.d.h.a$c.a(Camera2.kt:18)
	at com.camerakit.d.h.a$c.onCaptureCompleted(Camera2.kt:4)
	at android.hardware.camera2.impl.CameraCaptureSessionImpl$1.lambda$onCaptureCompleted$3$CameraCaptureSessionImpl$1(CameraCaptureSessionImpl.java:693)
	at android.hardware.camera2.impl.-$$Lambda$CameraCaptureSessionImpl$1$OA1Yz_YgzMO8qcV8esRjyt7ykp4.run(Unknown Source:8)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:236)
	at android.os.HandlerThread.run(HandlerThread.java:67)
[ 2023-04-27T18:37:42.830    10251: 25369: 25848 E/AndroidRuntime  ] FATAL EXCEPTION: CameraHandler@1682591861378
Process: com.ms.ailiao, PID: 25369
java.lang.UnsupportedOperationException: The producer output buffer format 0x7fa30c04 doesn't match the ImageReader's configured buffer format 0x21.
	at android.media.ImageReader.nativeImageSetup(Native Method)
	at android.media.ImageReader.acquireNextSurfaceImage(ImageReader.java:465)
	at android.media.ImageReader.acquireNextImage(ImageReader.java:519)
	at android.media.ImageReader.acquireLatestImage(ImageReader.java:412)
	at com.camerakit.d.h.a$c.a(Camera2.kt:18)
	at com.camerakit.d.h.a$c.onCaptureCompleted(Camera2.kt:4)
	at android.hardware.camera2.impl.CameraCaptureSessionImpl$1.lambda$onCaptureCompleted$3$CameraCaptureSessionImpl$1(CameraCaptureSessionImpl.java:693)
	at android.hardware.camera2.impl.-$$Lambda$CameraCaptureSessionImpl$1$OA1Yz_YgzMO8qcV8esRjyt7ykp4.run(Unknown Source:8)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:236)
	at android.os.HandlerThread.run(HandlerThread.java:67)
[ 2023-04-27T18:37:50.710        0:   688:  1349 I/LSPosedLogcat   ] !!refresh_verbose!!
-----part 5 end----

**Comment by fuckgithubh** [comment]
测试过mi8 mi9pro android11/9/10/12 google系统均存在此问题
